---
kind: Namespace
apiVersion: v1
metadata:
  name: ns1
  labels:
    name: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ns1
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.image.repository }}"
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: UUID
            value: "$(POD_NAME)"
          - name: AUTHOR
            value:  {{ .Values.AUTHOR }}
